FROM mcr.microsoft.com/dotnet/aspnet:10.0.11-noble-chiseled@sha256:0839314d08bb65da369135389a5d8291f75ace587fbb0488f469eb92c62eef68 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 9001

FROM mcr.microsoft.com/dotnet/sdk:10.0.400-noble@sha256:e1fc6e423f543119c406d24e2e687d67c569f18f04a37a8b0005d80ad0dcee80 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY [".editorconfig", "."]
COPY ["Directory.Build.props", "."]
COPY ["src/UnfoldedCircle.Electrolux/UnfoldedCircle.Electrolux.csproj", "UnfoldedCircle.Electrolux/"]
RUN dotnet restore "UnfoldedCircle.Electrolux/UnfoldedCircle.Electrolux.csproj" --locked-mode
COPY ./src .

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR "/src/UnfoldedCircle.Electrolux"
RUN dotnet publish "UnfoldedCircle.Electrolux.csproj" -c "$BUILD_CONFIGURATION" -o /app/publish /p:PublishTrimmed=false /p:PublishSingleFile=true /p:UseAppHost=true
RUN touch /app/publish/configured_entities.json /app/publish/token.json && \
    chown "$APP_UID" /app/publish/configured_entities.json /app/publish/token.json && \
    chmod 644 /app/publish/configured_entities.json /app/publish/token.json

FROM base AS final
USER $APP_UID
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./driver"]